#!/usr/bin/env python
import requests
import time
import datetime
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
import xml.etree.ElementTree as ET

#fwhost can be either an IP address or a DNS record - enter it below between the quotation marks
#for an IP address, it would look like: fwhost = "192.168.1.1"
#for a DNS object, it would look like: fwhost = "fwmanagement.yourdomain.com"
fwhost = ""

#fwkey is the API key that is generated by the firewall for the account that the API will impersonate
#You can generate the key using the following URL to the firewall:
#https://<firewall>/api?type=keygen&user=<username>&password=<password>
#The response will be in XML and the key will be between the <key> and </key> tags
#Copy that entire key into the variable below between the quotation marks
fwkey = ""


values = {'type': 'op', 'cmd': '<show><session><info></info></session></show>', 'key': fwkey}
palocall = 'https://' + fwhost + '/api'

while (1==1):
	cpslog = open('cpslog.csv', 'a')
	r = requests.post(palocall, data=values, verify=False)
	print r.text

	tree = ET.fromstring(r.text)
	stamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d %H:%M:%S')
	cps = tree.find('result').find('cps').text
	active = tree.find('result').find('num-active').text
	log = stamp + "," + cps + "," + active + "\n"
	cpslog.write(log)
	cpslog.close()
	time.sleep(1)
